// Generated by CoffeeScript 1.6.3
var MainView, RemoteClient, actions, models;

require("./views/components");

MainView = require("./views/main");

models = require("./models");

RemoteClient = require("./client");

window.actions = actions = require("./actions")(models);

window.xpath = require("xpgen")();

window.expect = require("expect.js");

window.client = new RemoteClient();

client.on("reload", function() {
  return window.location.reload();
});

$(document).ready(function() {
  var main;
  main = new MainView();
  return main.attach($("#application"));
});

mocha.setup({
  reporter: require("./reporters/mocha")(models, client),
  ui: "bdd",
  timeout: 1000 * 9999
});
