// Generated by CoffeeScript 1.6.3
var MainView, RemoteClient, Url, actions, findXPath, models, q, _ref;

if (typeof window.console === "undefined") {
  window.console = {};
  window.console.log = window.console.warn = window.console.error = function() {};
}

require("./views/components");

MainView = require("./views/main");

models = require("./models");

RemoteClient = require("./client");

Url = require("url");

findXPath = require("./utils/findXPath");

window.actions = actions = require("./actions")(models);

window.xpath = require("xpgen")();

window.expect = require("expect.js");

window.client = new RemoteClient();

client.on("reload", function() {
  return window.location.reload();
});

client.on("runTests", function() {
  return mocha.run();
});

$(document).ready(function() {
  var main;
  main = new MainView();
  return main.attach($("#application"));
});

mocha.setup({
  reporter: require("./reporters/mocha")(models, client),
  ui: "bdd",
  timeout: 1000 * 9999
});

q = (_ref = Url.parse(window.location.href, true).query) != null ? _ref : {};

client.ready(function() {
  return mocha.run();
});
