// Generated by CoffeeScript 1.6.3
var StatusView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

StatusView = (function(_super) {
  __extends(StatusView, _super);

  function StatusView() {
    _ref = StatusView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  StatusView.prototype.paper = require("./status.pc");

  StatusView.prototype.bindings = {
    "models.successCount": "successCount",
    "models.failureCount": "failureCount",
    "models.testDuration": "testDuration"
  };

  return StatusView;

})(require("mojojs").View);

module.exports = StatusView;

