// Generated by CoffeeScript 1.6.3
var Url, express, httpProxy;

express = require("express");

httpProxy = require("http-proxy");

Url = require("url");

exports.require = ["express.server", "config", "http.public", "sock.server"];

exports.load = function(app, config, pubsub) {
  var proxy, urlInfo;
  urlInfo = Url.parse(config.get("proxy"));
  proxy = new httpProxy.RoutingProxy();
  proxy.on("start", function(req, res, target) {
    var oldRequest;
    oldRequest = target.protocol.request;
    if (oldRequest.__shimed) {
      return;
    }
    target.protocol.request = function(req, cb) {
      return oldRequest.call(target.protocol, req, function(res) {
        var _ref;
        if (((_ref = res.statusCode) === 301 || _ref === 302) && res.headers.location) {
          res.headers.location = res.headers.location.replace("http,", "");
        }
        return cb(res);
      });
    };
    return target.protocol.request.__shimed = true;
  });
  return pubsub.on("init", function() {
    return app.all("/**", function(req, res) {
      var p;
      return p = proxy.proxyRequest(req, res, {
        host: urlInfo.hostname,
        port: urlInfo.port
      });
    });
  });
};
