// Generated by CoffeeScript 1.6.3
var browserify, express;

express = require("express");

browserify = require("browserify-middleware");

exports.require = ["express.server", "tests", "mediator"];

exports.load = function(expressServer, tests, mediator) {
  return mediator.on("pre open", function(msg, next) {
    expressServer.use("/test", express["static"](__dirname));
    expressServer.use("/test/js/app.bundle.js", browserify(__dirname + "/js/index.js"));
    expressServer.use("/test/js/scripts.bundle.js", browserify(tests.bundle()));
    return next();
  });
};
