// Generated by CoffeeScript 1.6.3
var browserify, express;

express = require("express");

browserify = require("browserify-middleware");

exports.require = ["express.server", "tests", "pubsub"];

exports.load = function(expressServer, tests, pubsub) {
  return pubsub.subscribe("init", function() {
    expressServer.use("/test", express["static"](__dirname));
    expressServer.use("/test/js/app.bundle.js", browserify(__dirname + "/js/index.js"));
    return expressServer.use("/test/js/scripts.bundle.js", browserify(tests.bundle()));
  });
};
