// Generated by CoffeeScript 1.6.3
var browserify, express;

express = require("express");

browserify = require("browserify-middleware");

exports.require = ["express.server", "tests"];

exports.plugin = function(expressServer, tests) {
  var stat;
  stat = express["static"](__dirname);
  expressServer.use("/test", function(req, res, next) {
    console.log(req.headers);
    return stat(req, res, next);
  });
  expressServer.use("/test/js/app.bundle.js", browserify(__dirname + "/js/index.js"));
  return expressServer.use("/test/js/scripts.bundle.js", browserify(tests.bundle()));
};
