// Generated by CoffeeScript 1.6.3
var gaze;

gaze = require("gaze");

exports.require = ["tests"];

exports.plugin = function(tests) {
  console.log(tests.search);
  return gaze(tests.search, function() {
    return this.on("all", tests.bundle);
  });
};
