// Generated by CoffeeScript 1.6.3
/*
  waits for browsers, then kills cortado
  after all browsers have completed
*/

exports.require = ["sock.clients", "config"];

exports.load = function(clients, config) {
  var hasErrors, keepAlive, killProcess, numRunning, tryKilling;
  keepAlive = config.get("keepAlive");
  numRunning = 0;
  hasErrors = 0;
  killProcess = function() {
    return setTimeout((function() {
      return process.exit(Number(hasErrors));
    }), 100);
  };
  tryKilling = function() {
    if (!--numRunning && !keepAlive) {
      return killProcess();
    }
  };
  return clients.on("client", function(client) {
    var onClose;
    client.on("startTests", function() {
      return numRunning++;
    });
    client.on("close", onClose = function() {
      hasErrors = true;
      console.error("(%s) closed unexpectedly", client);
      return tryKilling();
    });
    return client.on("endTests", function(info) {
      client.removeListener("close", onClose);
      hasErrors = hasErrors || info.failureCount > 0;
      return tryKilling();
    });
  });
};

