// Generated by CoffeeScript 1.6.3
var gaze;

gaze = require("gaze");

exports.require = ["tests", "config"];

exports.plugin = function(tests, config) {
  if (!config.get("keepAlive")) {
    return;
  }
  return gaze(tests.search, function() {
    return this.on("all", tests.bundle);
  });
};
