// Generated by CoffeeScript 1.6.3
var async;

async = require("async");

exports.require = ["browser.launchers.*", "config"];

exports.plugin = function(launcher, config) {
  var browsers, limit;
  browsers = config.get("browsers") || [];
  limit = config.get("limit") || 1;
  return async.eachLimit(browsers, limit, (function(browser, next) {
    var name, version, _ref;
    return _ref = browser.split("@"), name = _ref[0], version = _ref[1], _ref;
  }), function() {
    return console.log("DONE");
  });
};
