// Generated by CoffeeScript 1.6.2
(function() {
  var Url, express, httpProxy, startServer;

  express = require("express");

  httpProxy = require("http-proxy");

  Url = require("url");

  startServer = function(options) {
    var proxy, server, urlInfo;

    proxy = new httpProxy.RoutingProxy();
    server = express();
    urlInfo = Url.parse(options.proxy);
    return server.all("/**", function(req, res) {
      return proxy.proxyRequest(req, res, {
        host: urlInfo.hostname,
        port: urlInfo.port
      });
    });
  };

  exports.start = function(config) {
    startServer(config);
    express;
    return console.log(config);
  };

}).call(this);
