// Generated by CoffeeScript 1.6.3
var Client,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Client = (function(_super) {
  __extends(Client, _super);

  /*
  */


  function Client(_con, _clients) {
    this._con = _con;
    this._clients = _clients;
    this._onMessage = __bind(this._onMessage, this);
    this._onClose = __bind(this._onClose, this);
    this._onOpen = __bind(this._onOpen, this);
    this._con.on("data", this._onMessage);
    this.on("open", this._onOpen);
    this._con.on("close", this._onClose);
    this.name = "Browser";
  }

  /*
  */


  Client.prototype.send = function(data) {
    return this._con.write(JSON.stringify(data));
  };

  /*
  */


  Client.prototype._onOpen = function(data) {
    this.platform = data.platform;
    this.name = this.platform.name + "@" + this.platform.version.split(".").shift();
    return this.send({
      event: "ready"
    });
  };

  /*
  */


  Client.prototype._onClose = function() {
    return this.emit("close");
  };

  /*
  */


  Client.prototype.toString = function() {
    return this.name;
  };

  /*
  */


  Client.prototype._onMessage = function(event) {
    var d;
    if (!event) {
      return;
    }
    d = JSON.parse(event);
    d.client = this;
    this.emit(d.event, d.data);
    this.emit("event", d);
    return this._clients.emit(d.event, d);
  };

  return Client;

})(require("events").EventEmitter);

module.exports = Client;

