// Generated by CoffeeScript 1.6.3
var sockjs;

sockjs = require("sockjs");

exports.require = ["http.server"];

exports.plugin = function(httpServer) {
  var sock;
  sock = sockjs.createServer({
    sockjs_url: "http://cdn.sockjs.org/sockjs-0.3.min.js",
    log: function() {}
  });
  sock.installHandlers(httpServer, {
    prefix: "/sock"
  });
  return sock;
};
