// Generated by CoffeeScript 1.6.3
var events;

events = require("events");

exports.load = function() {
  var em;
  em = new events.EventEmitter();
  return {
    publish: function() {
      return em.emit.apply(em, arguments);
    },
    subscribe: function() {
      return em.on.apply(em, arguments);
    }
  };
};

