// Generated by CoffeeScript 1.6.2
(function() {
  var Cortado;

  Cortado = (function() {
    /*
    */
    function Cortado() {}

    return Cortado;

  })();

  module.exports = function() {
    return new Cortado();
  };

}).call(this);
