// Generated by CoffeeScript 1.6.3
var Logger;

Logger = (function() {
  /*
  */

  function Logger(name) {
    var label;
    label = "(" + name + ")";
    while (label.length < 12) {
      label += " ";
    }
    this._label = label;
  }

  /*
  */


  Logger.prototype.log = function() {};

  return Logger;

})();

exports.plugin = function() {
  var create;
  create = function(name) {};
  return {
    get: function(name) {}
  };
};
