// Generated by CoffeeScript 1.6.3
var request, spawn;

spawn = require("child_process").spawn;

request = require("request");

exports.require = ["config", "pubsub"];

exports.load = function(config, pubsub) {
  var notifier, port, startNotifier;
  port = 18493;
  startNotifier = function() {
    var proc;
    proc = spawn(__dirname + "/../../../node_modules/.bin/node-osx-notifier", [port]);
    proc.on("error", function() {});
    return proc.on("exit", function() {
      return setTimeout(startNotifier, 1000 * 5);
    });
  };
  startNotifier();
  notifier = {
    notify: function(data) {
      var path, req;
      path = data.type;
      req = request.get("http://localhost:" + port + "/" + path + "?message=" + (encodeURIComponent(String(data.message))) + "&title=Cortado");
      return req.on("error", function() {});
    }
  };
  pubsub.subscribe("notify", function(data) {
    return notifier.notify(data);
  });
  pubsub.subscribe("error", function(err) {
    return notifier.notify({
      type: "fail",
      message: err.message
    });
  });
  pubsub.subscribe("success", function(data) {
    return notifier.notify({
      type: "pass",
      message: data.message
    });
  });
  return notifier;
};
