// Generated by CoffeeScript 1.6.3
var LogrollView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LogrollView = (function(_super) {
  __extends(LogrollView, _super);

  function LogrollView() {
    _ref = LogrollView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  LogrollView.prototype.paper = require("./index.pc");

  LogrollView.prototype.sections = {
    logs: {
      type: "list",
      source: "models.logs",
      modelViewClass: require("./log")
    }
  };

  return LogrollView;

})(require("mojojs").View);

module.exports = LogrollView;
