// Generated by CoffeeScript 1.6.3
var bindable;

bindable = require("bindable");

exports.plugin = function(plugin) {
  var p;
  p = plugin.params();
  p.cwd = process.cwd();
  return new bindable.Object(p);
};
