// Generated by CoffeeScript 1.6.3
exports.require = ["sock.clients", "tests"];

exports.plugin = function(clients, tests) {
  return tests.on("bundle", function() {
    console.log("tests changed, updating clients");
    return clients.emit("reload");
  });
};
