// Generated by CoffeeScript 1.6.3
var Client,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Client = (function(_super) {
  __extends(Client, _super);

  /*
  */


  function Client(_con) {
    this._con = _con;
    this._onMessage = __bind(this._onMessage, this);
    this._con.on("data", this._onMessage);
  }

  /*
  */


  Client.prototype.send = function(data) {
    return this._con.write(JSON.stringify(data));
  };

  /*
  */


  Client.prototype._onMessage = function(event) {
    var d;
    if (!event) {
      return;
    }
    d = JSON.parse(event);
    this.emit(d.event, d.data);
    return this.emit("event", d);
  };

  return Client;

})(require("events").EventEmitter);

module.exports = Client;
