// Generated by CoffeeScript 1.6.3
var plugin;

plugin = require("plugin");

require("colors");

exports.start = function(options) {
  var plug;
  plug = plugin().params(options).require(__dirname + "/plugins");
  return plug.load(function(err) {
    if (err) {
      console.error(err.stack);
    }
    return plug.exports.pubsub.publish("init");
  });
};
