// Generated by CoffeeScript 1.6.3
exports.require = ["config", "pubsub"];

exports.load = function(config, pubsub) {
  var events, name, _ref, _results;
  events = (_ref = config.get("events")) != null ? _ref : {};
  _results = [];
  for (name in events) {
    _results.push(pubsub.subscribe(name, events[name]));
  }
  return _results;
};
