// Generated by CoffeeScript 1.6.3
exports.require = ["config", "mediator"];

exports.load = function(config, mediator) {
  var events, name, _ref, _results;
  events = (_ref = config.get("events")) != null ? _ref : {};
  _results = [];
  for (name in events) {
    console.log(name);
    _results.push(mediator.on(name, events[name]));
  }
  return _results;
};
