// Generated by CoffeeScript 1.6.3
exports.require = ["config", "tests"];

exports.load = function(config, tests) {
  var fn;
  if (!(fn = config.get("reload"))) {
    return;
  }
  return tests.on("bundle", fn);
};

