// Generated by CoffeeScript 1.6.3
var Tester, Url, async;

async = require("async");

Tester = require("./tester");

Url = require("url");

exports.require = ["browser.launchers.*", "sock.clients", "tests", "config", "pubsub"];

exports.plugin = function(launcher, clients, tests, config, pubsub) {
  var browsers, limit, ops, proxyInfo, running, tester, _ref, _ref1;
  browsers = config.get("browsers") || [];
  limit = config.get("limit") || 1;
  proxyInfo = Url.parse(config.get("proxy"));
  ops = {
    host: (_ref = (_ref1 = config.get("host")) != null ? _ref1 : proxyInfo.hostname) != null ? _ref : "localhost",
    port: config.get("port")
  };
  if (!browsers.length) {
    return;
  }
  running = false;
  tester = {
    run: function() {
      if (running) {
        return;
      }
      running = true;
      return async.eachLimit(browsers, limit, (function(browser, next) {
        return tester = new Tester(launcher, browser, clients, ops).run(next);
      }), function(err) {
        var hasError;
        running = false;
        hasError = false;
        if (err != null) {
          return hasError = true;
        }
      });
    }
  };
  return pubsub.subscribe("init", tester.run);
};
