// Generated by CoffeeScript 1.6.3
var EventEmitter, Tester,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EventEmitter = require("events").EventEmitter;

Tester = (function(_super) {
  __extends(Tester, _super);

  /*
  */


  function Tester(_launcher, browser, clients, _ops) {
    var _ref;
    this._launcher = _launcher;
    this.browser = browser;
    this.clients = clients;
    this._ops = _ops;
    _ref = this.browser.split("@"), this.browserName = _ref[0], this.browserVersion = _ref[1];
  }

  /*
  */


  Tester.prototype.run = function(next) {
    var _this = this;
    this._launcher.start(this.browser, "http://" + this._ops.host + ":" + this._ops.port + "/test", function(err, browser) {
      var listener;
      if (err != null) {
        return next(err);
      }
      return _this.clients.on("open", listener = function(event) {
        var client, name, p, version;
        p = event.data.platform;
        version = p.version.split(".").shift();
        name = p.name.toLowerCase();
        client = event.client;
        if (name !== _this.browserName || version !== _this.browserVersion) {
          return;
        }
        _this.clients.removeListener("open", listener);
        client.send({
          event: "runTests"
        });
        return client.once("endTests", function(result) {
          var errors, _ref;
          errors = (_ref = result.errors) != null ? _ref.map(function(err) {
            return err.message;
          }).join("\n") : void 0;
          browser.stop();
          return next();
        });
      });
    });
    return this;
  };

  return Tester;

})(EventEmitter);

module.exports = Tester;
