// Generated by CoffeeScript 1.6.3
var Tester;

Tester = (function() {
  /*
  */

  function Tester(_launcher, browser, clients) {
    var _ref;
    this._launcher = _launcher;
    this.browser = browser;
    this.clients = clients;
    _ref = this.browser.split("@"), this.browserName = _ref[0], this.browserVersion = _ref[1];
  }

  /*
  */


  Tester.prototype.run = function(next) {
    var _this = this;
    console.log("opening %s", this.browser);
    return this._launcher.start(this.browser, "http://student.classdojo.dev:8083/test", function(err, browser) {
      var listener;
      if (err != null) {
        return next(err);
      }
      return _this.clients.on("open", listener = function(event) {
        var client, name, p, version;
        p = event.data.platform;
        version = p.version.split(".").shift();
        name = p.name.toLowerCase();
        client = event.client;
        if (name !== _this.browserName || version !== _this.browserVersion) {
          return;
        }
        console.log("(%s) running tests", _this.browser);
        _this.clients.removeListener("open", listener);
        client.send({
          event: "runTests"
        });
        client.on("test", function(data) {
          if (data.error) {
            console.error("(%s) ✘", _this.browser, data.description);
            return console.error("(%s)  ", _this.browser, data.error.message);
          } else {
            return console.log("(%s) ✔", _this.browser, data.description);
          }
        });
        return client.once("endTests", function(result) {
          console.log("(%s) success: %d, errors: %d, duration: %s ", _this.browser, result.successCount, result.failureCount, result.duration + " s");
          return next();
        });
      });
    });
  };

  return Tester;

})();

module.exports = Tester;
