// Generated by CoffeeScript 1.6.3
var IFrame, hurryup, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

hurryup = require("hurryup");

IFrame = (function(_super) {
  __extends(IFrame, _super);

  function IFrame() {
    _ref = IFrame.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  IFrame.prototype.define = ["onLoad", "src", "class", "id"];

  /*
  */


  IFrame.prototype._onRender = function() {
    var attr, iframe, _fn, _i, _len, _ref1,
      _this = this;
    IFrame.__super__._onRender.call(this);
    iframe = document.createElement("iframe");
    this.bind("onLoad").to(function(onLoad) {
      if (iframe.attachEvent) {
        return iframe.attachEvent("onload", onLoad);
      } else {
        return iframe.onload = onLoad;
      }
    }).now();
    _ref1 = ["src", "class", "id"];
    _fn = function(attr) {
      return _this.bind(attr).to(function(value) {
        if (value === void 0) {
          return;
        }
        if (/class|id/.test(attr)) {
          return iframe.setAttribute(attr, value);
        } else {
          return iframe[attr.toLowerCase()] = value;
        }
      }).now();
    };
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      attr = _ref1[_i];
      _fn(attr);
    }
    return this.section.append(iframe);
  };

  return IFrame;

})(require("mojojs").View);

module.exports = IFrame;
