// Generated by CoffeeScript 1.6.3
var http;

http = require("http");

exports.require = ["express.server", "config"];

exports.load = function(expressServer, config) {
  var httpServer, p, _ref;
  httpServer = http.createServer(expressServer);
  httpServer.listen(p = (_ref = config.get("port")) != null ? _ref : 8083);
  console.log("listening on http port %d", p);
  return httpServer;
};

