// Generated by CoffeeScript 1.6.3
var Preview, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Preview = (function(_super) {
  __extends(Preview, _super);

  function Preview() {
    this._onIFrameLoad = __bind(this._onIFrameLoad, this);
    _ref = Preview.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  Preview.prototype.define = ["location"];

  /*
  */


  Preview.prototype.paper = require("./index.pc");

  /*
  */


  Preview.prototype.bindings = {
    "models.control.location": "location",
    "location": function(v) {
      return this.set("models.control.document", void 0);
    }
  };

  /*
  */


  Preview.prototype._onIFrameLoad = function() {
    var $iframe, doc, e, iframe, win;
    try {
      $iframe = this.$("iframe");
      iframe = $iframe[0];
      doc = $iframe.contents()[0];
      win = iframe.contentWindow || iframe;
      if (win.location.pathname === "/test") {
        return win.location = "/";
      }
      if (doc === document) {
        return;
      }
      this.set("models.control.document", doc);
      return this.set("models.control.window", win);
    } catch (_error) {
      e = _error;
      console.warn(e);
      return this.set("models.control.document", document);
    }
  };

  return Preview;

})(require("mojojs").View);

module.exports = Preview;
