// Generated by CoffeeScript 1.6.3
var gaze;

gaze = require("gaze");

exports.require = ["config", "tests"];

exports.load = function(config, tests) {
  var watch;
  watch = config.get("watch");
  if (!watch || !config.get("keepAlive")) {
    return;
  }
  console.log("watching %s", watch.join("\n"));
  return gaze(watch, function() {
    return this.on("all", tests.bundle);
  });
};
