// Generated by CoffeeScript 1.6.3
var gaze;

gaze = require("gaze");

exports.require = ["config", "tests"];

exports.plugin = function(config, tests) {
  var watch;
  watch = config.get("watch");
  if (!watch || !config.get("keepAlive")) {
    return;
  }
  console.log("watching %s", watch.join("\n"));
  return gaze(watch, function() {
    this.on("all", tests.bundle);
    this.on("all", function() {
      return console.log("GG");
    });
    return this.on("add", function() {
      return console.log("G");
    });
  });
};
