// Generated by CoffeeScript 1.6.3
var gaze;

gaze = require("gaze");

exports.require = ["config", "sock.clients.controls"];

exports.plugin = function(config, controls) {
  var watch;
  watch = config.get("watch");
  if (!watch) {
    return;
  }
  console.log("watching %s", watch);
  return gaze(watch, controls.reload);
};
