// Generated by CoffeeScript 1.6.3
exports.require = ["sock.clients", "tests", "pubsub"];

exports.plugin = function(clients, tests, pubsub) {
  var controls;
  controls = {
    reload: function() {
      return clients.send({
        event: "reload"
      });
    }
  };
  clients.on("client", function(client) {
    var browser,
      _this = this;
    browser = "Browser";
    client.on("open", function() {
      return browser = "" + client.platform.name + "@" + (client.platform.version.split('.').shift());
    });
    client.on("startTests", function(event) {
      pubsub.publish("notify", {
        type: "info",
        message: "" + browser + " - tests start"
      });
      return console.log("(%s)    start tests", browser);
    });
    client.on("test", function(data) {
      var inf;
      inf = "" + browser + " - " + data.description;
      if (data.error) {
        console.error("(%s) %s %s", browser, "✘".red, data.description);
        pubsub.publish("error", new Error(inf));
        return console.error("(%s)  ", browser, data.error.message);
      } else {
        console.log("(%s) %s %s", browser, "✔".green, data.description);
        return _this.emit("success", {
          message: inf
        });
      }
    });
    return client.on("endTests", function(result) {
      var inf;
      inf = "" + browser + " - success: " + result.successCount + ", errors: " + result.failureCount + ", duration: " + result.duration + " s";
      console.log("(%s)    %s", browser, "complete tests, success: " + result.successCount + ", errors: " + result.failureCount + ", duration: " + result.duration + " s");
      pubsub.publish("notify", {
        type: "info",
        message: inf
      });
      return pubsub.publish("completeTests");
    });
  });
  tests.on("bundle", controls.reload);
  return controls;
};
